### ISSUE TITLE
Add Custom Elements

### ISSUE THREAD

**Issue by furesoft** [ArchLeaders/Avalonia.SettingsFactory#1]
Hi there,

thanks for this awesome project but it would be awesome if you can extend it with custom controls and custom datatypes, like example for using DateTime or custom data with custom controls

**Comment by ArchLeaders** [comment]
That's a good idea, I'll see about implementing that when I get a chance.

And just to make sure I'm understanding correctly, you're looking for something like this, correct?
- Support for adding custom data type handlers
- More built-in handlers for generic types

**Comment by furesoft** [comment]
yeah, that's right.

**Comment by ArchLeaders** [comment]
Great, I'll post any updates here.

**Comment by furesoft** [comment]
Oh an option to add dynamicly add settings to the view from different models would be awesome grat. I have a fully modular application and each module is able to use custom settings

**Comment by ArchLeaders** [comment]
I would need to rework the library to get something like that working, cause it works very non-MVVM internally. But I should probably rewrite parts of it anyway, so I'll just keep that in mind when/if I get around it.

**Comment by ArchLeaders** [comment]
@furesoft any reason for closing this?

**Comment by furesoft** [comment]
I created my own control for my needs: https://github.com/furesoft/Slithin/blob/develop/Source/New/Modules/Slithin.Modules.Settings.UI/Builder/SettingsUIBuilderImpl.cs

**Comment by ArchLeaders** [comment]
Ah right, I'll leave this open cause I would still like to implement these plans in my library.

**Comment by ArchLeaders** [comment]
Features implemented in the rewrite: https://github.com/ArchLeaders/ConfigFactory
